---
- name: "Add the official OpenVPN APT key; hiding 25 lines of log..."
  apt_key:
    id: E158C569
    data: "{{ item }}"
  with_file: openvpn_signing.key
  no_log: True

- name: Install OpenVPN and its dependencies from APT
  apt:
    package:
      - openvpn
      - udev
